<?php

namespace Tests\Feature;

use Tests\Support\TestCase;

/**
 * Tables generated by FrontCrudController show relationships as linked
 * labels (through the child controller map) and expose charon's sorting
 * and filtering on the index page.
 */
class RelationshipAndQueryTest extends TestCase
{
    public function testIndexLinksRelatedResourcesToTheirShowPage()
    {
        $this->actingAsAuthorizedAdmin();
        $category = $this->seedCategory('Tools');
        $this->seedWidget('Hammer', ['category_id' => $category->id]);

        $response = $this->get('/admin/widgets');

        $response->assertStatus(200);
        $response->assertDontSee('relationship?');
        $this->assertMatchesRegularExpression(
            '#<a href="http://localhost/admin/categories/' . $category->id . '">\s*Tools\s*</a>#',
            $response->getContent()
        );
    }

    public function testRelatedResourcesWithoutAChildControllerAreLabelledButNotLinked()
    {
        $this->actingAsAuthorizedAdmin();
        $category = $this->seedCategory('Tools');
        $this->seedWidget('Hammer', ['category_id' => $category->id]);

        $response = $this->get('/admin/plain-widgets');

        $response->assertStatus(200);
        $response->assertSee('Tools');
        $response->assertDontSee('/admin/categories/' . $category->id);
    }

    public function testRelatedResourcesWhoseRouteCannotBeBuiltAreLabelledButNotLinked()
    {
        $this->actingAsAuthorizedAdmin();
        $category = $this->seedCategory('Tools');
        $this->seedWidget('Hammer', ['category_id' => $category->id]);

        $response = $this->get('/admin/nested-widgets');

        $response->assertStatus(200);
        $response->assertSee('Tools');
        $response->assertDontSee('/categories/' . $category->id);
    }

    public function testIndexHeadersSortTheCollection()
    {
        $this->actingAsAuthorizedAdmin();
        $this->seedWidget('Alpha');
        $this->seedWidget('Beta');

        $response = $this->get('/admin/widgets?sort=!name');

        $response->assertStatus(200);
        $response->assertSeeInOrder(['Beta', 'Alpha']);
        // the header link toggles back to ascending and shows the direction
        $response->assertSee('href="/admin/widgets?sort=name"', false);
        $response->assertSee('&#9660;', false);
    }

    public function testIndexFilterFormFiltersTheCollection()
    {
        $this->actingAsAuthorizedAdmin();
        $this->seedWidget('Alpha');
        $this->seedWidget('Beta');

        $response = $this->get('/admin/widgets?name=Alpha');

        $response->assertStatus(200);
        $response->assertSee('Alpha');
        $response->assertDontSee('Beta');
        $response->assertSee('<form method="get" action="/admin/widgets"', false);
        $this->assertMatchesRegularExpression('#<input[^>]*name="name"[^>]*value="Alpha"#', $response->getContent());
        $this->assertMatchesRegularExpression('#<select[^>]*name="status"#', $response->getContent());
    }

    public function testBlankFilterInputsDoNotFilter()
    {
        // Submitting the filter form sends every field, blank ones included.
        $this->actingAsAuthorizedAdmin();
        $this->seedWidget('Alpha');
        $this->seedWidget('Beta');

        $response = $this->get('/admin/widgets?name=&status=');

        $response->assertStatus(200);
        $response->assertSee('Alpha');
        $response->assertSee('Beta');
    }

    public function testShowRendersASingleRelationshipAsALinkedDetailRow()
    {
        $this->withoutExceptionHandling();
        $this->actingAsAuthorizedAdmin();
        $category = $this->seedCategory('Tools');
        $widget = $this->seedWidget('Hammer', ['category_id' => $category->id]);

        $response = $this->get('/admin/widgets/' . $widget->id);

        $response->assertStatus(200);
        $this->assertMatchesRegularExpression(
            '#<th>Category</th>\s*<td>\s*<a href="http://localhost/admin/categories/' . $category->id . '">\s*Tools\s*</a>#',
            $response->getContent()
        );
    }
}
